### PR TITLE
Save/Load selected mods

### PR DESCRIPTION
**Pull request by Skattered**
Save selected mods to text file on install, read from file on load and add to defaultmods list to check boxes
addresses #16

### CODE REVIEW

**Comment by Benik3** [comment]
Nice. What to save the txt file into folder like %AllUsersProfile%? So when you move the exe it will still work and you don't have to move the txt file...

**Comment by Skattered** [comment]
> Nice. What to save the txt file into folder like %AllUsersProfile%? So when you move the exe it will still work and you don't have to move the txt file...

That's not a bad idea, I just didn't want to leave remnants behind somewhere hidden if someone deletes the mod installer, this way they can see the file in the same dir they started.

**Comment by megalon** [comment]
I made a couple of adjustments, and addressed a case where the `mods.txt` file didn't exist.
Now that I think about it, the theme settings are currently stored using `Properties.Settings`, which saves to `C:\Users\username\AppData\Local\BeatSaberModManager\`

It would make sense to store the selected mods list here as well.

**Comment by Benik3** [comment]
Yes, that also make sense.

**Pull request merged**
