### PR TITLE
Material Skin and Dark Mode

### PR DESCRIPTION
**Pull request by LiNCHx**
I've updated the UI using the [Material Skin](https://github.com/IgnaceMaes/MaterialSkin) provided by IgnaceMaes and fixed a bug where the installation path was set to NULL when you click abort on the folder browse dialog.
You are also able to select a dark mode in the new options tab.

### CODE REVIEW

**Comment by megalon** [comment]
Wow, this looks great, thanks for making this!

I think that the dark theme could use a little color tweaking.
The categories are really hard to read, and I think that the dependencies highlighting is a bit too dark, but it's not that bad.

**Comment by megalon** [comment]
image
As you can see it's pretty hard to read the categories

**Comment by LiNCHx** [comment]
Yes, but I'm still trying to figure out how to change the color of the GroupNames. Apparently it's not that easy to change them. I gonna have to change them using an override or something like that :/

**Comment by megalon** [comment]
It looks like you can't change the color of the text for a ListViewGroup
https://stackoverflow.com/questions/3073389/win32-list-view-group-header-text-color

Instead of using ListViewGroups, we could have a single group and simply have each category label as a special `ListViewItem` with it's own color scheme.

I've noticed that there is no minimum window size when using the material skin, so it's possible to make the window disappear down to nearly a single pixel.

**Comment by megalon** [comment]
Going to go ahead and merge this, then add in the minimum size after, and make a few tweaks to the theme as well. Thanks!

**Comment by megalon** [comment]
I ended up reverting this merge because your branch has the dependencies code that does not work properly, and I was unable to easily remove it.
I'm going to try to remove it again from your fork, but for now I'd rather not have it in the master branch.

**Comment by LiNCHx** [comment]
Special colors for each category is a good idea! I'm going to start to implement it today. Did you think about custom ForeColors or BackColors?

**Pull request merged**
